-- AUTO-GENERATED by scripts/generate-permission-matrix.mjs. Do not edit manually.
CREATE OR REPLACE FUNCTION public.permission_matrix_allows(
  p_role TEXT,
  p_resource TEXT,
  p_action TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
IMMUTABLE
SET search_path = public
AS $$
BEGIN
  CASE p_role
    WHEN 'demo' THEN
      CASE p_resource
        WHEN 'tasks' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'polls' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'calendar' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'basecamp' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'links' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        ELSE RETURN FALSE;
      END
    WHEN 'super_admin' THEN
      CASE p_resource
        WHEN 'tasks' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'polls' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'calendar' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'basecamp' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'links' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        ELSE RETURN FALSE;
      END
    WHEN 'consumer_member' THEN
      CASE p_resource
        WHEN 'tasks' THEN RETURN p_action IN ('read', 'write', 'delete');
        WHEN 'polls' THEN RETURN p_action IN ('read', 'write', 'delete');
        WHEN 'calendar' THEN RETURN p_action IN ('read', 'write', 'delete');
        WHEN 'basecamp' THEN RETURN p_action IN ('read', 'write', 'delete');
        WHEN 'links' THEN RETURN p_action IN ('read', 'write', 'delete');
        ELSE RETURN FALSE;
      END
    WHEN 'consumer_guest' THEN
      CASE p_resource
        WHEN 'tasks' THEN RETURN FALSE;
        WHEN 'polls' THEN RETURN FALSE;
        WHEN 'calendar' THEN RETURN FALSE;
        WHEN 'basecamp' THEN RETURN FALSE;
        WHEN 'links' THEN RETURN FALSE;
        ELSE RETURN FALSE;
      END
    WHEN 'pro_admin' THEN
      CASE p_resource
        WHEN 'tasks' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'polls' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'calendar' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'basecamp' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'links' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        ELSE RETURN FALSE;
      END
    WHEN 'pro_editor' THEN
      CASE p_resource
        WHEN 'tasks' THEN RETURN p_action IN ('read', 'write', 'delete');
        WHEN 'polls' THEN RETURN p_action IN ('read', 'write');
        WHEN 'calendar' THEN RETURN p_action IN ('read', 'write', 'delete');
        WHEN 'basecamp' THEN RETURN p_action IN ('read');
        WHEN 'links' THEN RETURN p_action IN ('read', 'write');
        ELSE RETURN FALSE;
      END
    WHEN 'pro_viewer' THEN
      CASE p_resource
        WHEN 'tasks' THEN RETURN p_action IN ('read');
        WHEN 'polls' THEN RETURN p_action IN ('read', 'write');
        WHEN 'calendar' THEN RETURN p_action IN ('read');
        WHEN 'basecamp' THEN RETURN p_action IN ('read');
        WHEN 'links' THEN RETURN p_action IN ('read', 'write');
        ELSE RETURN FALSE;
      END
    WHEN 'pro_coordinator' THEN
      CASE p_resource
        WHEN 'tasks' THEN RETURN p_action IN ('read', 'write', 'delete');
        WHEN 'polls' THEN RETURN p_action IN ('read', 'write');
        WHEN 'calendar' THEN RETURN p_action IN ('read', 'write', 'delete');
        WHEN 'basecamp' THEN RETURN p_action IN ('read');
        WHEN 'links' THEN RETURN p_action IN ('read', 'write', 'delete');
        ELSE RETURN FALSE;
      END
    WHEN 'event_organizer' THEN
      CASE p_resource
        WHEN 'tasks' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'polls' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'calendar' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'basecamp' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        WHEN 'links' THEN RETURN p_action IN ('read', 'write', 'delete', 'admin');
        ELSE RETURN FALSE;
      END
    WHEN 'event_attendee' THEN
      CASE p_resource
        WHEN 'tasks' THEN RETURN p_action IN ('read');
        WHEN 'polls' THEN RETURN p_action IN ('read');
        WHEN 'calendar' THEN RETURN p_action IN ('read');
        WHEN 'basecamp' THEN RETURN p_action IN ('read');
        WHEN 'links' THEN RETURN p_action IN ('read');
        ELSE RETURN FALSE;
      END
    ELSE RETURN FALSE;
  END CASE;
END;
$$;
