// AUTO-GENERATED by scripts/generate-permission-matrix.mjs. Do not edit manually.
export type PermissionAction = 'read' | 'write' | 'delete' | 'admin';
export type PermissionResource = 'tasks' | 'polls' | 'calendar' | 'basecamp' | 'links';
export type PermissionRole =
  | 'demo'
  | 'super_admin'
  | 'consumer_member'
  | 'consumer_guest'
  | 'pro_admin'
  | 'pro_editor'
  | 'pro_viewer'
  | 'pro_coordinator'
  | 'event_organizer'
  | 'event_attendee';
export type PermissionRule = Record<PermissionAction, boolean>;
export type PermissionMatrix = Record<
  PermissionRole,
  Partial<Record<PermissionResource | '*', PermissionRule>>
>;
export const PERMISSION_MATRIX: PermissionMatrix = {
  demo: {
    '*': {
      read: true,
      write: true,
      delete: true,
      admin: true,
    },
  },
  super_admin: {
    '*': {
      read: true,
      write: true,
      delete: true,
      admin: true,
    },
  },
  consumer_member: {
    '*': {
      read: true,
      write: true,
      delete: true,
      admin: false,
    },
  },
  consumer_guest: {
    '*': {
      read: false,
      write: false,
      delete: false,
      admin: false,
    },
  },
  pro_admin: {
    '*': {
      read: true,
      write: true,
      delete: true,
      admin: true,
    },
  },
  pro_editor: {
    tasks: {
      read: true,
      write: true,
      delete: true,
      admin: false,
    },
    polls: {
      read: true,
      write: true,
      delete: false,
      admin: false,
    },
    calendar: {
      read: true,
      write: true,
      delete: true,
      admin: false,
    },
    basecamp: {
      read: true,
      write: false,
      delete: false,
      admin: false,
    },
    links: {
      read: true,
      write: true,
      delete: false,
      admin: false,
    },
  },
  pro_viewer: {
    tasks: {
      read: true,
      write: false,
      delete: false,
      admin: false,
    },
    polls: {
      read: true,
      write: true,
      delete: false,
      admin: false,
    },
    calendar: {
      read: true,
      write: false,
      delete: false,
      admin: false,
    },
    basecamp: {
      read: true,
      write: false,
      delete: false,
      admin: false,
    },
    links: {
      read: true,
      write: true,
      delete: false,
      admin: false,
    },
  },
  pro_coordinator: {
    tasks: {
      read: true,
      write: true,
      delete: true,
      admin: false,
    },
    polls: {
      read: true,
      write: true,
      delete: false,
      admin: false,
    },
    calendar: {
      read: true,
      write: true,
      delete: true,
      admin: false,
    },
    basecamp: {
      read: true,
      write: false,
      delete: false,
      admin: false,
    },
    links: {
      read: true,
      write: true,
      delete: true,
      admin: false,
    },
  },
  event_organizer: {
    '*': {
      read: true,
      write: true,
      delete: true,
      admin: true,
    },
  },
  event_attendee: {
    tasks: {
      read: true,
      write: false,
      delete: false,
      admin: false,
    },
    polls: {
      read: true,
      write: false,
      delete: false,
      admin: false,
    },
    calendar: {
      read: true,
      write: false,
      delete: false,
      admin: false,
    },
    basecamp: {
      read: true,
      write: false,
      delete: false,
      admin: false,
    },
    links: {
      read: true,
      write: false,
      delete: false,
      admin: false,
    },
  },
} as const;
